export const TOGGLE_TOP_PANEL = "TOGGLE_TOP_PANEL";
export const TOGGLE_MEDIA_GALLERY = "TOGGLE_MEDIA_GALLERY";
export const TOGGLE_BLACKLIST = "TOGGLE_BLACKLIST";
export const TOGGLE_SENDER_PAGE = "TOGGLE_SENDER_PAGE";
export const TOGGLE_PROFILE_PAGE = "TOGGLE_PROFILE_PAGE";
export const TOGGLE_MAILING_PAGE = "TOGGLE_MAILING_PAGE";
export const TOGGLE_ATTACHMENTS = "TOGGLE_ATTACHMENTS";
